language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

      # The following is required for netcdf files:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
install:
    - pip install -e .[testing,functions,server,tests]

script:
    - flake8
    - py.test -a 'not auth' --cov=src/pydap/
