language: python
python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - cython
      # The following as required for netcdf files:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev
install:
    # Install netcdf4-python from github. pip install does not
    # appear to be working:
    - pip install ordereddict
    - git clone https://github.com/Unidata/netcdf4-python.git
    - cd netcdf4-python
    - python setup.py build
    - python setup.py install
    - cd ..
    - rm -r netcdf4-python
    # Continue typical install:
    - travis_wait 30 pip install scipy
    - pip install -e .[testing,functions,tests]

script:
    - python setup.py nosetests -a '!auth'
