language: python
branches:
    only:
        - develop
        - 2to3
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
      - liblapack-dev
      - cython

install:
    - travis_wait 30 pip install scipy
    - pip install -e .[testing,functions,tests]

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4

script:
    - python setup.py nosetests
