name: pydap_tests
channels:
- conda-forge
dependencies:
- numpy < 2.0
- netCDF4
- pytest
- pytest-cov
- pytest-env
- codecov
- scipy
- pip
- pip:
  - werkzeug >= 2.2.2
  - cryptography
  - webtest
  - gsw
  - coards
  - testresources
  - requests-mock
