name: pydap_docs
channels:
- conda-forge
dependencies:
- python=3.11
- jupyter-book<2.0
- jupyterlab
- matplotlib
- cartopy
- xarray
- dask
- earthaccess
- netcdf4
- pip
- pip:
  - git+https://github.com/pydap/pydap.git
